### ISSUE TITLE
Теневой бан за ботоводство.

### ISSUE THREAD

**Issue by Nidelon** [KotRikD/pixelbot#13]
Я бы хотел предупредить что в пб добавили что-то вроде теневого бана при использовании бота, человек после не может участвовать, так как сервер перестает обрабатывать зарисовывание пикселей.
Кто хочет до конца пиксель баттла остаться, я бы рекомендовал им никак не пользоваться, даже исправленной с лолза.

**Comment by KotRikD** [comment]
Держу вкурсе, что этому бану 3 года (на пб 2020) минмум) Лолза исправления вообще используют браузерное расширение насколько я знаю, которое нарушает vk.com/terms п. 9.3, так что им тоже не советую пользоваться.

Любое ботоводство - всегда опасно :) Всё что могу посоветовать из того, что я помню, это использовать сокеты от новорегов, прокси и т.д. (базовая гигиена вообщем)

**Comment by Nidelon** [comment]
Но всё же просто предупреждаю других людей, на пб 2020 такого бана вообще даже не замечал, а тут те раз.
